#!/usr/bin/env bash
#  _       __      ____
# | |     / /___ _/ / /___  ____ _____  ___  _____
# | | /| / / __ `/ / / __ \/ __ `/ __ \/ _ \/ ___/
# | |/ |/ / /_/ / / / /_/ / /_/ / /_/ /  __/ /
# |__/|__/\__,_/_/_/ .___/\__,_/ .___/\___/_/
#                 /_/         /_/

WALLPAPER_DIR="$HOME/Pictures/Wallpaper"

# Slideshow behavior
while true; do
  CURRENT_WALL=$(swww query | sed 's/.*image: //')

  # Get a random wallpaper that is not the current one
  WALLPAPER=$(find "$WALLPAPER_DIR" -type f ! -name "$(basename "$CURRENT_WALL")" | shuf -n 1)

  # Apply the selected wallpaper
  swww img "$WALLPAPER" --transition-type random --transition-fps 60 &
  #
  # For swaylock to have the same Background
  cp "$WALLPAPER" ~/.current_wallpaper
  sleep 600
done
